services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: production
    volumes:
      - ./backend/src:/app/backend/src
    command: pnpm start:prod
    ports:
      - 4000:3000
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: production
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: pnpm dev
    ports:
      - 3000:3000
