import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 prose prose-slate prose-headings:mb-3 prose-p:mt-0 mx-auto">
        <h1 className="">Hello Everyone</h1>
        <p className="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae,
          ipsum corrupti rem vel exercitationem, quis optio, enim possimus
          dolorem quae repellat. Praesentium itaque, voluptas vel beatae maxime
          autem repellat tempora repudiandae voluptate adipisci explicabo
          debitis, repellendus nesciunt minima assumenda earum sit aliquam
          voluptatum laborum. Adipisci id mollitia molestias modi explicabo!
        </p>
        <p className="">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae,
          ipsum corrupti rem vel exercitationem, quis optio, enim possimus
          dolorem quae repellat. Praesentium itaque, voluptas vel beatae maxime
          autem repellat tempora{" "}
          <a href="">epudiandae voluptate adipisci explicabo debitis,</a>
          repellendus nesciunt minima assumenda earum sit aliquam voluptatum
          laborum. Adipisci id mollitia molestias modi explicabo!
        </p>
      </main>
    </>
  );
}
